language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.6
  - DJANGO_VERSION=1.11b1

install:
  - pip install Django==$DJANGO_VERSION
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt

script:
  - python runtests.py

matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.9.12
    - python: 3.3
      env: DJANGO_VERSION=1.10.6
    - python: 3.3
      env: DJANGO_VERSION=1.11b1
    - python: 3.6
      env: DJANGO_VERSION=1.9.12
    - python: 3.6
      env: DJANGO_VERSION=1.8.17
    - python: 3.6
      env: DJANGO_VERSION=1.10.6
